package category_products

import category_products.infrastructure.repository.CategoryProductRepositoryImpl
import shared.BaseMockedRepository

class CategoryProductsMockedRepository extends CategoryProductRepositoryImpl with BaseMockedRepository
