package authentication

import authentications.infrastructure.repository.AuthenticationRepositoryImpl
import shared.BaseMockedRepository

class AuthenticationMockedRepository extends AuthenticationRepositoryImpl with BaseMockedRepository
